import { AmenitieInput } from "../../API";

export const Amenities:AmenitieInput[] = [
  { label: "Wifi",                     value: "Wifi",                    icon: "CiWifiOn" },
  { label: "Pets Allowed",             value: "Pets Allowed",            icon: "FaPaw" },
  { label: "Parking Lot",              value: "Parking Lot",             icon: "FaParking" },
  { label: "Dine-In",                  value: "Dine-In",                 icon: "GiKnifeFork" },
  { label: "First Aid Kit",            value: "First Aid Kit",           icon: "GiHospitalCross" },
  { label: "Accepting Cash Only",      value: "Accepting Cash Only",     icon: "BsCashStack" },
  { label: "Reservation Required",     value: "Reservation Required",    icon: "BsFillCalendarCheckFill" },
  { label: "Smoking Room",             value: "Smoking Room",            icon: "MdOutlineSmokingRooms" },
  { label: "Restroom",                 value: "Restroom",                icon: "FaRestroom" },
  { label: "Gender-Neutral Washrooms", value: "Gender-Neutral Washrooms", icon: "BsGenderAmbiguous" },
  { label: "Air Conditioning",         value: "Air Conditioning",          icon: "TbAirConditioning" },
  { label: "Heating",                  value: "Heating",                   icon: "GiHeatHaze" },
  { label: "Laundry Service",          value: "Laundry Service",             icon: "MdLocalLaundryService" },
  { label: "Ironing Facilities",       value: "Ironing Facilities",          icon: "TbIroning1" },
  { label: "Elevator",                 value: "Elevator",                    icon: "GiElevator" },
  { label: "Room Service",             value: "Room Service",                icon: "MdCleaningServices" },
  { label: "Conference Room",          value: "Conference Room",             icon: "GiVideoConference" },
  { label: "Business Center",          value: "Business Center",             icon: "IoBusinessSharp" },
  { label: "High-Speed Internet",      value: "High-Speed Internet",           icon: "TiWiFi" },
  { label: "Printer Service",          value: "Printer Service",           icon: "AiFillPrinter" },
  { label: "Childcare Service",        value: "Childcare Service",         icon: "MdChildCare" },
  { label: "Swimming Pool",            value: "Swimming Pool",             icon: "FaSwimmingPool" },
  { label: "Playground",               value: "Playground",                icon: "MdOutlineBedroomBaby" },
  { label: "Airport Shuttle",          value: "Airport Shuttle",         icon: "MdAirportShuttle" },
  { label: "Car Rental Service",       value: "Car Rental Service",          icon: "MdCarRental" },
  { label: "Bicycle Rental",           value: "Bicycle Rental",            icon: "IoBicycleSharp" },
  { label: "Bus Service",              value: "Bus Service",               icon: "TbBusStop" },
  { label: "Breakfast Buffet",         value: "Breakfast Buffet",                icon: "MdFreeBreakfast" },
  { label: "Coffee Shop",              value: "Coffee Shop",                   icon: "BiCoffeeTogo" },
  { label: "Bar",                      value: "Bar",                         icon: "BiSolidDrink" },
  { label: "Restaurant",               value: "Restaurant",                  icon: "RiRestaurant2Fill" },
  { label: "Vending Machines",         value: "Vending Machines",              icon: "GiVendingMachine" },
  { label: "Delivery",                 value: "Delivery",                      icon: "MdDeliveryDining" },
  { label: "Currency Exchange",        value: "Currency Exchange",             icon: "MdCurrencyExchange" },
  { label: "ATM",                      value: "ATM",                           icon: "MdLocalAtm" },
  { label: "Concierge Service",        value: "Concierge Service",             icon: "FaConciergeBell" },
  { label: "Luggage Storage",          value: "Luggage Storage",               icon: "LuLuggage" },
  { label: "Ticket Service",           value: "Ticket Service",                icon: "BsFillTicketDetailedFill" },
  { label: "Gym",                      value: "Gym",                             icon: "CgGym" },
  { label: "Spa",                      value: "Spa",                             icon: "BiSolidSpa" },
  { label: "Sauna",                    value: "Sauna", icon: "MdOutlineMeetingRoom" },
  { label: "Game Room",                value: "Game Room", icon: "FaGamepad" },
  { label: "Theater",                  value: "Theater",                         icon: "FaTheaterMasks" },
];