export const categories:any = {
  'Resturants': 'fa-kit fa-user-chef',
  'Fast Food': 'fa-solid fa-burger',
  "Today's Events": 'fa-solid fa-calendar',
  'Transportation': 'fa-solid fa-car',
  'Hotels': 'fa-solid fa-hotel',
  'Sports': 'fa-solid fa-basketball',
  'Entertainment': 'fa-solid fa-video',
  'Arts & Culture': 'fa-solid fa-paintbrush',
  'Fitness': 'fa-solid fa-dumbbell',
  'Beauty': 'fa-solid fa-person-dress',
  'Health': 'fa-solid fa-notes-medical',
  'Banking/Finance': 'fa-solid fa-building-columns',
  'Clothing': 'fa-solid fa-shirt',
  'Specialty Stores': 'fa-solid fa-shop',
  'Shoes': 'fa-solid fa-shoe-prints',
  'Gaming': 'fa-solid fa-gamepad',
  'Electronics': 'fa-solid fa-laptop',
  'Home Renovation': 'fa-solid fa-screwdriver-wrench',
  'Landscaping': 'fa-solid fa-leaf',
  'Plumbing': 'fa-solid fa-toilet',
  'Electrical': 'fa-solid fa-bolt',
  'Heating & Cooling': 'fa-solid fa-temperature-three-quarters',
  'Construction': 'fa-solid fa-hammer',
  'Big Box Stores': 'fa-solid fa-boxes-stacked',
  'Auto Repair & Dealerships': 'fa-solid fa-warehouse',
  'Books & Literature': 'fa-solid fa-book',
  'Grocery Stores': 'fa-solid fa-cart-shopping',
  'Farmers Market': 'fa-solid fa-tractor',
  'Cable & Satellite': 'fa-solid fa-satellite-dish',
  'Cell Phone': 'fa-solid fa-mobile-screen',
  'Tourism': 'fa-solid fa-plane',
  'Recreation': 'fa-solid fa-umbrella-beach'
};

export const CategoriesSelect = [
  { value: '*', label: 'All Categories' },
  { value: 'Resturants', label: 'Restaurants' },
  { value: 'Fast Food', label: 'Fast Food' },
  { value: "Today's Events", label: "Today's Events" },
  { value: 'Transportation', label: 'Transportation' },
  { value: 'Hotels', label: 'Hotels' },
  { value: 'Sports', label: 'Sports' },
  { value: 'Entertainment', label: 'Entertainment' },
  { value: 'Arts & Culture', label: 'Arts & Culture' },
  { value: 'Fitness', label: 'Fitness' },
  { value: 'Beauty', label: 'Beauty' },
  { value: 'Health', label: 'Health' },
  { value: 'Banking/Finance', label: 'Banking/Finance' },
  { value: 'Clothing', label: 'Clothing' },
  { value: 'Specialty Stores', label: 'Specialty Stores' },
  { value: 'Shoes', label: 'Shoes' },
  { value: 'Gaming', label: 'Gaming' },
  { value: 'Electronics', label: 'Electronics' },
  { value: 'Home Renovation', label: 'Home Renovation' },
  { value: 'Landscaping', label: 'Landscaping' },
  { value: 'Plumbing', label: 'Plumbing' },
  { value: 'Electrical', label: 'Electrical' },
  { value: 'Heating & Cooling', label: 'Heating & Cooling' },
  { value: 'Construction', label: 'Construction' },
  { value: 'Big Box Stores', label: 'Big Box Stores' },
  { value: 'Auto Repair & Dealerships', label: 'Auto Repair & Dealerships' },
  { value: 'Books & Literature', label: 'Books & Literature' },
  { value: 'Grocery Stores', label: 'Grocery Stores' },
  { value: 'Farmers Market', label: 'Farmers Market' },
  { value: 'Cable & Satellite', label: 'Cable & Satellite' },
  { value: 'Cell Phone', label: 'Cell Phone' },
  { value: 'Tourism', label: 'Tourism' },
  { value: 'Recreation', label: 'Recreation' },
];